#!/bin/bash

test_connection () 
{
output=$(nmcli radio wifi) 
echo $output
if [[ "$output" = "włączone" ]] ; then 
    echo  -e "####\nWifi is enabled\n"
else
    echo -e "####\nWifi is not enabled\n"
fi
}

ping_func ()
{
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then 
	echo 'Ping works - you can connect' 
else
	echo "Ping does not work - connection is not possible" 
fi
} 

test_connection
ping_func
